// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FvsEU6spJn_jwYK3P78X3r3GVbjjzZE',
    appId: '1:936079448326:web:f4371d1a872a658e4f2687',
    messagingSenderId: '936079448326',
    projectId: 'sms-mirror-47328',
    authDomain: 'sms-mirror-47328.firebaseapp.com',
    databaseURL: 'https://sms-mirror-47328-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-mirror-47328.firebasestorage.app',
    measurementId: 'G-SECGRRZ3TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMctBJ40paBpHEUWChKt0oqcFIqXUscsU',
    appId: '1:936079448326:android:1e5a089788135e794f2687',
    messagingSenderId: '936079448326',
    projectId: 'sms-mirror-47328',
    databaseURL: 'https://sms-mirror-47328-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-mirror-47328.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAdj8QVl9D5JXkSQ8iBagsDDOtb2u4LSI',
    appId: '1:936079448326:ios:3f3298d7cdc6cd724f2687',
    messagingSenderId: '936079448326',
    projectId: 'sms-mirror-47328',
    databaseURL: 'https://sms-mirror-47328-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-mirror-47328.firebasestorage.app',
    iosBundleId: 'com.example.smsMirror',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAdj8QVl9D5JXkSQ8iBagsDDOtb2u4LSI',
    appId: '1:936079448326:ios:3f3298d7cdc6cd724f2687',
    messagingSenderId: '936079448326',
    projectId: 'sms-mirror-47328',
    databaseURL: 'https://sms-mirror-47328-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-mirror-47328.firebasestorage.app',
    iosBundleId: 'com.example.smsMirror',
  );
}
